// -----------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Mono.Data.Sqlite;
using System.Data;
using System.Xml;
using UnityEngine;
using System.IO;

namespace AssemblyCSharpfirstpass
{
	public class PrepareMuisc:MonoBehaviour
	{
		MusicMGR mMusicManager;
		public UISlider mProgressBar;
		private float mStartTime;
		private int mStep;
		void Start()
		{
			mMusicManager = MusicMGR.instance();
			mProgressBar.sliderValue = 0.2f;
			mStartTime = Time.time;
			mStep = 1;
		}
	
		void Update()
		{

			switch(mStep)
			{
			case 1: //waiting network version request
				if(mProgressBar.sliderValue < 0.3f)
					mProgressBar.sliderValue = (Time.time - mStartTime)/5.0f;
				else
					mStep ++;
				break;
			case 2:
				if(mProgressBar.sliderValue < 0.7f)
				{
					mProgressBar.sliderValue = 0.3f + (Time.time - mStartTime)/5.0f;

				}
				else
					mStep ++;
				break;
			case 3:
				if(mProgressBar.sliderValue < 1.0f)
				{
					mProgressBar.sliderValue = 0.3f + (Time.time - mStartTime)/5.0f;
				}
				else
					Application.LoadLevel("startScene");
				break;
			default:
				break;

			}

		}
	}
}

