// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.IO;
using System.IO.Compression;
using System.Text;
using ICSharpCode.SharpZipLib.Zip;
using ICSharpCode.SharpZipLib.Core;

namespace AssemblyCSharpfirstpass
{
	public class BaseInitScript:MonoBehaviour
	{
		void Start()
		{

			//if(Directory.Exists(Application.dataPath + "/local_music") == false)
			if(false)
			{
				Debug.Log ("create local music directory");
				Directory.CreateDirectory(Application.dataPath + "/local_music");

				Debug.Log ("unzipping local music zip file");
				for(int i =1;i <= 2 ;i ++)
				{
					string file_path = string.Format("{0}",(120000 + i));
					string output_path = Application.dataPath + "/local_music/" + file_path;
					Directory.CreateDirectory(output_path);
					string asset_name = string.Format("songs/{0}",file_path);
					TextAsset zip_data = Resources.Load(asset_name) as TextAsset;
					ZipUtils.unzipMusicZip(zip_data.bytes,output_path);
//					File.WriteAllBytes(Application.dataPath + "/local/music/" + (12000 +1));
				}
			

			}
		}
		void Update()
		{
		}
		

			
		}
	}
	
	