// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharpfirstpass
{
	public class CameraEventProxy
	{
		private int mBackUPID;
		private string mDialogName = "Dialog";
		private int mDialogID;

		public static CameraEventProxy script = new CameraEventProxy();
		public static CameraEventProxy instance()
		{
				return script;
		}

		private CameraEventProxy()
		{

			mDialogID = 1<< LayerMask.NameToLayer(mDialogName);
		}
		public void setDialogEventLayerName(string _name)
		{
				mDialogName = _name;
		}

		public void disableDefaultEventMask(UICamera _camera)
		{
			mBackUPID = _camera.eventReceiverMask ; 
			_camera.eventReceiverMask = mDialogID;
		}
		public void enableDefaultEventMask(UICamera _camera)
		{
			_camera.eventReceiverMask = mBackUPID;
		}

	}
}

