// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Security.Cryptography;
using System.Text;
using UnityEngine;


namespace AssemblyCSharpfirstpass
{
	public class URLEncryption
	{
		private static readonly DateTime REFERENCE = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

		private static readonly string secretKey = "424bcebba457bc7b410ae0b9b54d011e";
		

		public URLEncryption ()
		{

		}
		private static Int64 toSeconds()
		{
			DateTime current_time = DateTime.UtcNow;
			return (Int64)((current_time - REFERENCE).TotalSeconds*1000);
		}
		private static string sign(SortedList _data,string _url)
		{
			MD5 md5Hash = MD5.Create ();

			StringBuilder joined = new StringBuilder ();
			for (int i = 0; i < _data.Count; i ++) 
			{

				joined.Append(_data.GetByIndex(i));
				joined.Append ("&");
			}
			joined.Append(_url);
			byte[] md5_data = md5Hash.ComputeHash (Encoding.UTF8.GetBytes (joined.ToString()));
			string base64String = System.Convert.ToBase64String (md5_data);
			return base64String;
		}
		public static string encryptURL(string _url,SortedList _params)
		{
			string device_id = DataService.instance().DEVICE_ID;
			Int64 time_passed = toSeconds ();
			string time = String.Format("%u",time_passed);
			_params.Add ("timestamp", time);
			_params.Add ("uid", device_id);
			_params.Add ("secret_key", secretKey);

			string sign_data = sign (_params,_url);
			Debug.Log ("sign_data:" + sign_data);

			_params.Remove ("timestamp");
			_params.Remove ("uid");
			_params.Remove ("secret_key");
			Debug.Log ("device_id:" + device_id + "time offset:" + time_passed);
			string signature = String.Format("timestamp=%u&uid=%s&signature%s",time_passed,device_id,sign_data);

			return signature;
		}
	}
}

